### PR TITLE
Add package.json

### LINKED ISSUE #8: Adding a package.json
## TL;DR
Please add a `package.json` to the root of the repository so that libflac.js can be used in other JS-based projects more easily using npm.

---
Hi, thanks for making this library. I am currently using libflac.js in [Jitsi Meet](https://github.com/jitsi/jitsi-meet) to encode recorded audio in the browser. 

Because of the set up of the project, it is better if we can reference libflac.js as a npm package. The only missing part for that to happen is a `package.json` file in the root of the repository. Currently, I am maintaining a fork, but the only modification is the addition of `package.json`. I think it is better if this is done by you guys.

I have created a simple pull request #7 and filled in the file for you. You don't have to use my PR.

You don't necessarily need to publish libflac.js to npmjs.com, because npm can treat git repository as a package as long as there is a `package.json` file in the root. Just adding a package.json file can make it much easier for other projects to use libflac.js.

### PR DESCRIPTION
**Pull request by ztl8702**
Adds a package.json to the root of the repository so that libflac.js can be used in other JS-based projects more easily using npm.

Fixes #8

### CODE REVIEW

**Comment by russaa** [comment]
thanks for contributing

one small issue with the PR:
the `package.json` makes reference to `"main": "index.js",` which is not included in the PR.

Did you forget to include it?
I'm guessing it imports one of the library files in `/dist` an makes it available?

**Comment by ztl8702** [comment]
@russaa  Well, that's actually a tough question. `"main": "index.js"` is meant to define an entry point, which will be invoked when people do `require('libflac')` or `import 'libflac'`. However, because of the `.mem` and `.wasm` files that need to be loaded dynamically, libflac.js cannot currently be used this way (i.e. as a node/requirejs/webpack module that is bundled with the user's js code). 

While it is probably possible to enable such usage later on, I suggest currently using a placeholder `index.js` to direct people to the documentation page.

**Comment by ztl8702** [comment]
This is what happens if I `require()` one of the files in `dist/`.

So it appears that what is exposed currently is the Emscripten module, not the public interface (`Flac` object). 


image

Perhaps adding `module.export=Flac` to `libflac_post.js` will help. Need to test it out.

**Comment by russaa** [comment]
yes, `emscripten` includes some generic code by default, that exports the its `Module` definition.

I think the best option would be an UMD wrapper, i.e. try to detect the environment and export as CommonJS or AMD module, or a global variable.

But it should be backwards compatible, i.e. by default export to global variable, so the UMD wrapper needs a little customization.

I'll have a look at it.

**Comment by russaa** [comment]
OK, I added an UMD wrapper (and fixed binary-loading for Node.js) and opened a PR on your repo/branch

**Pull request merged**
